name: Build
on:
  push:
    paths-ignore::
      - "README.md"

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [debug, release]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build ${{ matrix.os }} - ${{ matrix.target }}
        uses: actions/checkout@v3.5.3
      - run: make ${{ matrix.target }}
