name: Docker Build on ZeroTier TCP Relay

on:
  push:
    branches:
      - master     # 当 master 分支有推送时触发
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          echo "FILE_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          docker build --network host . -f Dockerfile -t zerotier-tcp-relay-build


      - name: Save Docker image
        run: |
          docker save zerotier-tcp-relay-build \
            | gzip > $GITHUB_WORKSPACE/zerotier-tcp-relay-build.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@master
        if: ${{ ! cancelled() }}
        with:
          name: ${{ env.FILE_DATE }}zerotier-tcp-relay-build.tar.gz
          path: zerotier-tcp-relay-build.tar.gz
