name: Build
on:
  push:
    paths-ignore::
      - "README.md"

jobs:
  lint:
    name: Run lint checks
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Lint
        uses: actions/checkout@v3.5.3
      - run: make lint

  build_matrix:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [debug, release]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build ${{ matrix.os }} - ${{ matrix.target }}
        timeout-minutes: 6
        uses: actions/checkout@v3.5.3
      - run: make ${{ matrix.target }}
